---
- name: Create Nginx Server
  hosts: webserver
  tasks: 
  - name: add epel release
    yum:
      name: epel-release
      state: present
  - name: install nginx server
    yum: 
      name: nginx
      state: present
  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: start nginx service
    service:
      name: nginx
      state: started
