---
- name: Create Nginx Server
  hosts: webserver
  tasks: 
  - name: install nginx server
    yum:
      name: epel-release
      state: present
    yum: 
      name: nginx=1.18.0-0ubuntu1.2
      state: present
  - name: start nginx service
    service:
      name: nginx
      state: started
